name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v1.0.1
      - uses: actions/checkout@v2
      - run:
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{
          github.repository_owner }} --password-stdin
      - run: earthly --push --use-inline-cache --save-inline-cache +filter-feed
      - run: earthly --push --use-inline-cache +filter-feed --VERSION=latest
      - run: earthly --push --use-inline-cache --save-inline-cache +ui
      - run: earthly --push --use-inline-cache +ui --VERSION=latest

