name: Build

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.5.10
      - uses: actions/checkout@v2
      - run:
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{
          github.repository_owner }} --password-stdin
      - run: earthly --push +filter-feed
      - run: earthly --push +filter-feed --VERSION=latest
